version: "1.0"

services:
  frontend:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    networks:
      - react-spring
    depends_on:
      - backend

  backend:
    build: ./server
    container_name: server
    restart: always
    ports:
      - '8080:8080'
    networks:
      - spring-redis
      - react-spring
    depends_on:
      - redis

  redis:
    container_name: redis
    hostname: redis
    restart: always
    image: redis:alpine3.17
    networks:
      - spring-redis
    volumes:
      - redis_data:/data
    expose:
      - 6379

networks:
  react-spring:
  spring-redis:

volumes:
  redis_data:



